name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: baby-1l-run-8

      - name: Run neutronics
        shell: bash -l {0}
        working-directory: analysis/neutron
        run: |
          python openmc_model.py
          jupyter-nbconvert --to notebook postprocessing.ipynb --execute

      - name: Run tritium model
        shell: bash -l {0}
        working-directory: analysis/tritium
        run: jupyter-nbconvert --to notebook tritium_model.ipynb --execute